const GET_GALLERY_CATEGORY = "GET_GALLERY_CATEGORY";
const GET_DATAS = "GET_DATAS";
const GET_ORDER_COUNT = "GET_ORDER_COUNT";
const GET_IS_READ_REVIEW_COUNT = "GET_IS_READ_REVIEW_COUNT";
const GET_ERRORS = "GET_ERRORS";

export {
   GET_GALLERY_CATEGORY,
   GET_DATAS,
   GET_ORDER_COUNT,
   GET_IS_READ_REVIEW_COUNT,
   GET_ERRORS,
};
