const GET_DATAS = "GET_DATAS";
const GET_COLLECTIONS = "GET_COLLECTIONS";
const GET_BRANDS = "GET_BRANDS";
const GET_CATEGORIES = "GET_CATEGORIES";
const GET_SUB_CATEGORIES = "GET_SUB_CATEGORIES";
const GET_COLORS = "GET_COLORS";
const GET_SIZES = "GET_SIZES";
const GET_SIZE_NUMBERS = "GET_SIZE_NUMBERS";
const GET_WEIGHTS = "GET_WEIGHTS";
const GET_EDIT_DATA = "GET_EDIT_DATA";
const GET_PRODUCT_IMAGES_DATA = "GET_PRODUCT_IMAGES_DATA";
const GET_SUBMIT_ERRORS = "GET_SUBMIT_ERRORS";

export {
  GET_DATAS,
  GET_COLLECTIONS,
  GET_BRANDS,
  GET_CATEGORIES,
  GET_SUB_CATEGORIES,
  GET_COLORS,
  GET_SIZES,
  GET_SIZE_NUMBERS,
  GET_WEIGHTS,
  GET_EDIT_DATA,
  GET_PRODUCT_IMAGES_DATA,
  GET_SUBMIT_ERRORS,
};
