const GET_DATA = "GET_DATA";
const POST_DATA = "POST_DATA";
const EDIT_DATA = "EDIT_DATA";
const UPDATE_DATA = "UPDATE_DATA";
const DELETE_DATA = "DELETE_DATA";
const ERROR = "ERROR";

export { GET_DATA, POST_DATA, EDIT_DATA, UPDATE_DATA, DELETE_DATA, ERROR };
