const GET_GALLERY_CATEGORIES = "GET_GALLERY_CATEGORIES";
const GET_DATAS = "GET_DATAS";
const GET_DATA = "GET_DATA";
const GET_ERRORS = "GET_ERRORS";

export { GET_GALLERY_CATEGORIES, GET_DATAS, GET_DATA, GET_ERRORS };
