const GET_DATAS = "GET_DATAS";
const GET_CATEGORIES = "GET_CATEGORIES";
const GET_EDIT_DATA = "GET_EDIT_DATA";
const GET_SUBMIT_ERRORS = "GET_SUBMIT_ERRORS";

export { GET_DATAS, GET_CATEGORIES, GET_EDIT_DATA, GET_SUBMIT_ERRORS };
