const GET_BRANDS = "GET_BRANDS";
const GET_CATEGORY_DATAS = "GET_CATEGORY_DATAS";
const GET_DATAS = "GET_DATAS";
const GET_ERRORS = "GET_ERRORS";
const GET_EDIT_DATA = "GET_EDIT_DATA";
const GET_PRODUCT_DATAS = "GET_PRODUCT_DATAS";
const GET_SUB_CATEGORY_DATAS = "GET_SUB_CATEGORY_DATAS";

export {
  GET_BRANDS,
  GET_CATEGORY_DATAS,
  GET_DATAS,
  GET_EDIT_DATA,
  GET_ERRORS,
  GET_PRODUCT_DATAS,
  GET_SUB_CATEGORY_DATAS,
};
